### ISSUE TITLE
use filepicker: allow Quest-creators to add images

### ISSUE THREAD

**Issue by sautille** [smuenzinger/questackular#101]
to the quest

**Comment by sautille** [comment]
Direct to S3 File Uploads in Node.js https://devcenter.heroku.com/articles/s3-upload-node

**Comment by Newms34** [comment]
Add to future features?

**Comment by sautille** [comment]
current issues:
- 'filepicker' input type is not correctly displayed when accessed via link 
  (it works when accessed via /create/quest)
- does the code have to be within a function? when does it get called
