### ISSUE TITLE
Select mode always on.

### ISSUE THREAD

**Issue by Newms34** [smuenzinger/questackular#336]
I'm adding a form (i.e., two radio buttons) to turn it off, but I may need some input on how to get that to background.js

**Comment by sautille** [comment]
OK do it, and if it works, pls merge that to master as soon as you can. thanks!

**Comment by sautille** [comment]
Error: [$parse:syntax] http://errors.angularjs.org/1.3.15/$parse/syntax?p0=%3D%3D&p1=is%20unexpected%2C%20expecting%20%5B%3A%5D&p2=9&p3=%7BselMode%3D%3D"<button class="btn btn-sm btn-primary" id="save-content" ng-disabled="selMode==&quot;off&quot;" ng-class="{selMode==&quot;on&quot;:btn-primary}" ng-click="saveContent()">"n%22%3Abtn-primary%7D&p4=%3D%3D%on%22%3Abtn-primary%7D
