### ISSUE TITLE
Dave can't even heroku

### ISSUE THREAD

**Issue by Newms34** [smuenzinger/questackular#360]
Apparently I'm an idiot, because I can't even figure out how to push to heroku. Can I not do that if I'm not the owner? Anyway, the browser/js/home/home.html on HEROKU needs to match the one on Sarah's GIT. Just in case anyone else can figure it out! I'll take another look tomorrow, but I don't wanna screw anything up...

**Comment by sarahzinger** [comment]
Hey @Newms34, I know this ticket is from a million years ago but I think you can do heroku stuff! I just did it and I'm not the heroku owner, Yvonne is. If you're still buggin, let me know and we can try to work on it together.
